<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\SalesRecord;

class SalesRecordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing data
        SalesRecord::truncate();
        
        // Generate realistic historical data for 2020-2024 with growth trends and seasonality
        $baseYear = 2020;
        $yearlyGrowthRate = 1.12; // 12% average annual growth
        
        for ($year = 2020; $year <= 2024; $year++) {
            // Calculate year progression factor (0-4 for 2020-2024)
            $yearIndex = $year - $baseYear;
            
            // Base sales increases each year with growth rate
            $yearBaseSales = 850000 * pow($yearlyGrowthRate, $yearIndex);
            
            for ($month = 1; $month <= 12; $month++) {
                // Seasonal multipliers (meat business has higher sales in certain months)
                $seasonalMultipliers = [
                    1 => 0.85,  // January - Post-holiday slowdown
                    2 => 0.90,  // February - Valentine's day boost
                    3 => 0.95,  // March
                    4 => 1.00,  // April - Easter season
                    5 => 1.05,  // May - Summer grilling season starts
                    6 => 1.10,  // June - Peak grilling season
                    7 => 1.12,  // July - Peak summer
                    8 => 1.08,  // August - Back to school
                    9 => 1.00,  // September
                    10 => 1.15, // October - Holiday prep begins
                    11 => 1.25, // November - Thanksgiving prep
                    12 => 1.35  // December - Christmas & New Year peak
                ];
                
                // Calculate monthly sales with seasonal variation
                $monthlySales = ($yearBaseSales / 12) * $seasonalMultipliers[$month];
                
                // Add random variation (±8%)
                $randomVariation = 1 + (rand(-8, 8) / 100);
                $totalSales = round($monthlySales * $randomVariation, 2);
                
                // Calculate realistic expense breakdown aligned with other reports
                // Utilities: 3-6% of sales
                $utilities = round($totalSales * (rand(30, 60) / 1000), 2);
                
                // Payroll: 12-18% of sales (according to memory: expense aligned with sales)
                $payroll = round($totalSales * (rand(120, 180) / 1000), 2);
                
                // Cost of Goods Sold (COGS): 45-55% of sales (primary expense for meat business)
                $cogs = round($totalSales * (rand(450, 550) / 1000), 2);
                
                // Other expenses: 2-5% of sales (maintenance, supplies, etc.)
                $otherExpenses = round($totalSales * (rand(20, 50) / 1000), 2);
                
                // Total expenses
                $totalExpenses = $utilities + $payroll + $cogs + $otherExpenses;
                
                // Net profit
                $netProfit = round($totalSales - $totalExpenses, 2);
                
                SalesRecord::create([
                    'year' => $year,
                    'month' => $month,
                    'total_sales' => $totalSales,
                    'total_expenses' => $totalExpenses,
                    'net_profit' => $netProfit
                ]);
            }
        }
        
        // Generate 2025 data (automated)
        // This will be automatically generated by the controller when accessed
        $this->command->info('Realistic historical sales data (2020-2024) seeded successfully!');
        $this->command->info('Data includes:');
        $this->command->info('  • Year-over-year growth trend (12% annual average)');
        $this->command->info('  • Seasonal variations (peak in Dec, Nov; low in Jan, Feb)');
        $this->command->info('  • Realistic expense breakdown aligned with industry standards');
        $this->command->info('2025 data will be automatically generated when the sales analytics page is accessed.');
    }
}