<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\SalesRecord;

class SalesRecordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing data
        SalesRecord::truncate();
        
        // Generate historical data for 2020-2024
        for ($year = 2020; $year <= 2024; $year++) {
            for ($month = 1; $month <= 12; $month++) {
                // Generate realistic sales data
                $baseSales = rand(80000, 120000);
                $totalSales = $baseSales + rand(0, 40000); // Range: 80,000 - 160,000
                $totalExpenses = $totalSales * (rand(60, 80) / 100); // 60-80% of sales
                $netProfit = $totalSales - $totalExpenses;
                
                SalesRecord::create([
                    'year' => $year,
                    'month' => $month,
                    'total_sales' => $totalSales,
                    'total_expenses' => $totalExpenses,
                    'net_profit' => $netProfit
                ]);
            }
        }
        
        // Generate 2025 data (automated)
        // This will be automatically generated by the controller when accessed
        $this->command->info('Historical sales data (2020-2024) seeded successfully!');
        $this->command->info('2025 data will be automatically generated when the sales analytics page is accessed.');
    }
}